services:
  adguardhome:
    image: adguard/adguardhome:v0.107.66
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
      - "192.168.1.50:53:53/tcp"
      - "192.168.1.50:53:53/udp"
    volumes:
      - /srv/data/adguard/work:/opt/adguardhome/work
      - /srv/data/adguard/conf:/opt/adguardhome/conf
