services:
  jellyfin:
    image: jellyfin/jellyfin:10.10.7
    restart: unless-stopped
    ports:
      - "127.0.0.1:8096:8096"
    volumes:
      - /srv/data/jellyfin/config:/config
      - /srv/data/jellyfin/cache:/cache
      - /srv/data/media:/media:ro
